#cloud-config
packages:
 - curl
 - wget
 - jq
runcmd:
 - [ wget, "https://raw.githubusercontent.com/erjosito/azure-cloud-init/master/download_metadata.sh", >~/download_metadata.sh ]
 - [ chmod, 755, ~/download_metadata.sh ]
 - [ ~/download_metadata.sh ]
